#!/bin/bash

service mysql-server stop
service dnsmasq stop
service hostapd stop

sed -i '$d' /etc/dhcpcd.conf

> /etc/network/interfaces
echo source-directory /etc/network/interfaces.d >> /etc/network/interfaces

echo auto lo >> /etc/network/interfaces
echo iface lo inet loopback >> /etc/network/interfaces

echo iface eth0 inet manual >> /etc/network/interfaces

echo allow-hotplug wlan0 >> /etc/network/interfaces
echo iface wlan0 inet manual >> /etc/network/interfaces
echo    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf >> /etc/network/interfa
ces

echo allow-hotplug wlan1 >> /etc/network/interfaces
echo iface wlan1 inet manual >> /etc/network/interfaces
echo    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf >> /etc/network/interfa
ces
